// Code generated by gitlab.dev.extlabs.ru/core/go-kit-service-generator  DO NOT EDIT.
package health

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strings"

	"github.com/go-kit/kit/log"
	"github.com/go-kit/kit/tracing/opentracing"
	httptransport "github.com/go-kit/kit/transport/http"
	stdopentracing "github.com/opentracing/opentracing-go"
	"github.com/pkg/errors"
)

// NewHTTPClient returns an Service backed by an HTTP server living at the
// remote instance. We expect instance to come from a service discovery system,
// so likely of the form "host:port". We bake-in certain middlewares,
// implementing the client library pattern.
func NewHTTPClient(instance string, tracer stdopentracing.Tracer, logger log.Logger) (Service, error) {
	// Quickly sanitize the instance string.
	if !strings.HasPrefix(instance, "http") {
		instance = "http://" + instance
	}
	u, err := url.Parse(instance)
	if err != nil {
		return nil, err
	}

	// global client middlewares
	var options []httptransport.ClientOption
	if tracer != nil {
		options = append(
			options,
			httptransport.ClientBefore(opentracing.ContextToHTTP(tracer, logger)),
		)
	}

	return endpoints{
		GetLivenessEndpoint: httptransport.NewClient(
			"GET",
			copyURL(u, "/liveness"),
			encodeHTTPGetLivenessGetLivenessRequest,
			decodeHTTPGetLivenessGetLivenessRespone,
			options...,
		).Endpoint(),
		GetReadinessEndpoint: httptransport.NewClient(
			"GET",
			copyURL(u, "/readiness"),
			encodeHTTPGetReadinessGetReadinessRequest,
			decodeHTTPGetReadinessGetReadinessResponse,
			options...,
		).Endpoint(),
		GetVersionEndpoint: httptransport.NewClient(
			"GET",
			copyURL(u, "/version"),
			encodeHTTPGetVersionGetVersionRequest,
			decodeHTTPGetVersionGetVersionResponse,
			options...,
		).Endpoint(),
	}, nil
}

func copyURL(base *url.URL, path string) *url.URL {
	next := *base
	next.Path = path
	return &next
}

func encodeHTTPGetLivenessGetLivenessRequest(_ context.Context, r *http.Request, request interface{}) error {

	return nil
}
func encodeHTTPGetReadinessGetReadinessRequest(_ context.Context, r *http.Request, request interface{}) error {

	return nil
}
func encodeHTTPGetVersionGetVersionRequest(_ context.Context, r *http.Request, request interface{}) error {

	return nil
}

func decodeHTTPGetLivenessGetLivenessRespone(_ context.Context, r *http.Response) (interface{}, error) {
	if r.StatusCode != http.StatusOK {
		return nil, errors.New(r.Status)
	}
	var request GetLivenessRespone
	if err := json.NewDecoder(r.Body).Decode(&request); err != nil {
		return nil, errors.Wrap(err, "decode request body")
	}
	return request, nil
}

func decodeHTTPGetReadinessGetReadinessResponse(_ context.Context, r *http.Response) (interface{}, error) {
	if r.StatusCode != http.StatusOK {
		return nil, errors.New(r.Status)
	}
	var request GetReadinessResponse
	if err := json.NewDecoder(r.Body).Decode(&request); err != nil {
		return nil, errors.Wrap(err, "decode request body")
	}
	return request, nil
}

func decodeHTTPGetVersionGetVersionResponse(_ context.Context, r *http.Response) (interface{}, error) {
	if r.StatusCode != http.StatusOK {
		return nil, errors.New(r.Status)
	}
	var request GetVersionResponse
	if err := json.NewDecoder(r.Body).Decode(&request); err != nil {
		return nil, errors.Wrap(err, "decode request body")
	}
	return request, nil
}
