// Code generated by gitlab.dev.extlabs.ru/core/go-kit-service-generator  DO NOT EDIT.
package health

import "context"

type Service interface {

	// GetLiveness The kubelet uses liveness probes to know when to restart a Container
	GetLiveness(context.Context, *GetLivenessRequest) (*GetLivenessRespone, error)

	// GetReadiness The kubelet uses readiness probes to know when a Container is ready to start accepting traffic
	GetReadiness(context.Context, *GetReadinessRequest) (*GetReadinessResponse, error)

	// GetVersion Check buid time, last commit and version app
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
}
